# generated by datamodel-codegen:
#   filename:  lineage.schema.json

from pydantic import BaseModel, ConfigDict, Field, constr
from enum import StrEnum
from typing import Literal


class TableLineageItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    source: constr(min_length=1) = Field(
        ..., description="The upstream (feeding) model name."
    )
    target: constr(min_length=1) = Field(
        ..., description="The downstream (consuming) model name."
    )


class LineageType(StrEnum):
    pass_through = "pass-through"
    rename = "rename"
    transformation = "transformation"
    filter = "filter"
    join = "join"
    unknown = "unknown"


class Column(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    source_column: constr(min_length=1) = Field(
        ..., alias="sourceColumn", description="Column name in the source model."
    )
    target_column: constr(min_length=0) = Field(
        ...,
        alias="targetColumn",
        description="Column name in the target model. Empty for structural edges (filter/join/unknown).",
    )
    lineage_type: LineageType = Field(
        ...,
        alias="lineageType",
        description="Values: pass-through, rename, transformation, filter, join, unknown.",
    )


class ColumnLineageItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    source: constr(min_length=1) = Field(
        ..., description="The upstream (feeding) model name."
    )
    target: constr(min_length=1) = Field(
        ..., description="The downstream (consuming) model name."
    )
    columns: list[Column] = Field(..., description="Column-level lineage mappings.")


class LineageSchema(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    field_schema: Literal[
        "https://raw.githubusercontent.com/thealtoclef/dbt-mdl/main/jsonschema/lineage.schema.json"
    ] = Field(
        "https://raw.githubusercontent.com/thealtoclef/dbt-mdl/main/jsonschema/lineage.schema.json",
        alias="$schema",
        description="the schema of lineage",
    )
    catalog: str = Field(..., description="Catalog name.")
    schema_: str = Field(..., alias="schema", description="Schema name.")
    data_source: str = Field(
        ...,
        alias="dataSource",
        description="Data source type (e.g., BIGQUERY, SNOWFLAKE, POSTGRES).",
    )
    table_lineage: list[TableLineageItem] = Field(
        ...,
        alias="tableLineage",
        description="Table-level lineage edges. Each edge represents a data flow from a source model to a target model.",
    )
    column_lineage: list[ColumnLineageItem] = Field(
        ..., alias="columnLineage", description="Column-level lineage edges."
    )
