# generated by datamodel-codegen:
#   filename:  mdl.schema.json

from pydantic import BaseModel, ConfigDict, Field, constr
from enum import StrEnum
from typing import Any, Literal


class TableReference(BaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    catalog: str | None = None
    schema_: str | None = Field(None, alias="schema")
    table: constr(min_length=1)


type Model = constr(min_length=1)


class JoinType(StrEnum):
    one_to_one = "ONE_TO_ONE"
    one_to_many = "ONE_TO_MANY"
    many_to_one = "MANY_TO_ONE"
    many_to_many = "MANY_TO_MANY"


class Relationship(BaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    name: constr(min_length=1) = Field(..., description="the name of the relationship")
    models: list[Model] = Field(
        ..., description="the list of models", max_length=2, min_length=2
    )
    join_type: JoinType = Field(
        ..., alias="joinType", description="the join type of the relationship"
    )
    condition: constr(min_length=1) = Field(
        ..., description="the condition of the relationship"
    )
    properties: (
        dict[str, str | float | bool | dict[str, Any] | list[Any] | None] | None
    ) = Field(None, description="the customize properties of the relationship")


class DatePart(StrEnum):
    year = "YEAR"
    quarter = "QUARTER"
    month = "MONTH"
    week = "WEEK"
    day = "DAY"
    hour = "HOUR"
    minute = "MINUTE"
    second = "SECOND"


class TimeGrainItem(BaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    name: constr(min_length=1) = Field(
        ..., description="the name of the time grain field"
    )
    ref_column: constr(min_length=1) = Field(
        ...,
        alias="refColumn",
        description="the reference column name of the time grain field",
    )
    date_parts: list[DatePart] = Field(
        ...,
        alias="dateParts",
        description="the acceptable time units of the time grain field",
    )


class View(BaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    name: constr(min_length=1) = Field(..., description="the name of the view")
    statement: constr(min_length=1) = Field(
        ..., description="the sql statement of the view"
    )
    properties: (
        dict[str, str | float | bool | dict[str, Any] | list[Any] | None] | None
    ) = Field(None, description="the customize properties of the view")


class Value(BaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    name: constr(min_length=1) = Field(..., description="the name of the member")
    value: constr(min_length=1) | None = Field(
        None,
        description="the value of the member. If not provided, the value is the same as the name",
    )
    properties: (
        dict[str, str | float | bool | dict[str, Any] | list[Any] | None] | None
    ) = Field(None, description="the customize properties of the member")


class EnumDefinition(BaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    name: constr(min_length=1) = Field(..., description="the name of the enum")
    values: list[Value]
    properties: (
        dict[str, str | float | bool | dict[str, Any] | list[Any] | None] | None
    ) = Field(None, description="the customize properties of the enum")


class Operator(StrEnum):
    equals = "EQUALS"
    not_equals = "NOT_EQUALS"
    greater_than = "GREATER_THAN"
    less_than = "LESS_THAN"
    greater_than_or_equals = "GREATER_THAN_OR_EQUALS"
    less_than_or_equals = "LESS_THAN_OR_EQUALS"


class DataType(StrEnum):
    numeric = "NUMERIC"
    string = "STRING"


class Threshold(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    value: str = Field(..., description="the value of the threshold")
    data_type: DataType = Field(
        ..., alias="dataType", description="the data type of the threshold"
    )


class SessionProperty(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    name: constr(min_length=1) = Field(
        ..., description="the name of the session property"
    )
    required: bool = Field(
        ..., description="whether the session property is required or not"
    )
    default_expr: str | None = Field(
        None,
        alias="defaultExpr",
        description="the default SQL expression of the session property",
    )


class RowLevelAccessControl(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    name: str = Field(..., description="the name of the access-control rule")
    required_properties: list[SessionProperty] = Field(
        ...,
        alias="requiredProperties",
        description="the required properties for the access-control rule",
    )
    condition: str = Field(
        ...,
        description="The condition of the access-control rule. A condition is a SQL expression that evaluates to true or false.",
    )


class ColumnLevelAccessControl(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    name: str = Field(..., description="the name of the access-control rule")
    operator: Operator = Field(
        ..., description="the operator of the access-control rule"
    )
    required_properties: list[SessionProperty] = Field(
        ...,
        alias="requiredProperties",
        description="the required properties for the access-control rule",
        max_length=1,
        min_length=1,
    )
    threshold: Threshold | None = Field(
        None, description="the threshold value of the access-control rule"
    )


class Column(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    name: constr(min_length=1) = Field(..., description="the name of the column")
    type: constr(min_length=1) = Field(..., description="the type of the column")
    relationship: str | None = Field(
        None,
        description="the relationship used by the column. If the type is a relationship, this field is required",
    )
    is_calculated: bool | None = Field(
        None,
        alias="isCalculated",
        description="whether the column is calculated or not. If the column expression used relationship, this field is required",
    )
    not_null: bool | None = Field(
        None, alias="notNull", description="whether the column is not null or not"
    )
    expression: str | None = Field(
        None,
        description="the expression of the column. If the column is calculated, this field is required",
    )
    is_hidden: bool | None = Field(
        None, alias="isHidden", description="whether the column is hidden or not"
    )
    column_level_access_control: ColumnLevelAccessControl | None = Field(
        None,
        alias="columnLevelAccessControl",
        description="the access-control rule for the column",
    )
    properties: dict[str, str] | None = Field(
        None, description="the customize properties of the column"
    )


class Models(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    name: constr(min_length=1) = Field(..., description="the name of the model")
    ref_sql: constr(min_length=1) = Field(
        ..., alias="refSql", description="(WIP) the sql reference of the model"
    )
    base_object: constr(min_length=1) | None = Field(
        None, alias="baseObject", description="(WIP) the base object of the model"
    )
    table_reference: TableReference | None = Field(
        None, alias="tableReference", description="the table reference of the model"
    )
    columns: list[Column] | None = Field(None, description="the list of columns")
    primary_key: str | None = Field(
        None,
        alias="primaryKey",
        description="the primary key of the model. It's required if the model is the one side of any OEN_TO_MANY or MANY_TO_ONE relationship",
    )
    cached: bool | None = Field(
        None, description="(WIP) whether the model is cached or not"
    )
    refresh_time: constr(pattern=r"^\s*(\d+(?:\.\d+)?)\s*([a-zA-Z]+)\s*$") | None = (
        Field(
            None,
            alias="refreshTime",
            description="(WIP) the cache refresh time of the model",
        )
    )
    row_level_access_controls: list[RowLevelAccessControl] | None = Field(
        None, alias="rowLevelAccessControls"
    )
    properties: (
        dict[str, str | float | bool | dict[str, Any] | list[Any] | None] | None
    ) = Field(None, description="the customize properties of the model")


class Models1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    name: constr(min_length=1) = Field(..., description="the name of the model")
    ref_sql: constr(min_length=1) | None = Field(
        None, alias="refSql", description="(WIP) the sql reference of the model"
    )
    base_object: constr(min_length=1) = Field(
        ..., alias="baseObject", description="(WIP) the base object of the model"
    )
    table_reference: TableReference | None = Field(
        None, alias="tableReference", description="the table reference of the model"
    )
    columns: list[Column] | None = Field(None, description="the list of columns")
    primary_key: str | None = Field(
        None,
        alias="primaryKey",
        description="the primary key of the model. It's required if the model is the one side of any OEN_TO_MANY or MANY_TO_ONE relationship",
    )
    cached: bool | None = Field(
        None, description="(WIP) whether the model is cached or not"
    )
    refresh_time: constr(pattern=r"^\s*(\d+(?:\.\d+)?)\s*([a-zA-Z]+)\s*$") | None = (
        Field(
            None,
            alias="refreshTime",
            description="(WIP) the cache refresh time of the model",
        )
    )
    row_level_access_controls: list[RowLevelAccessControl] | None = Field(
        None, alias="rowLevelAccessControls"
    )
    properties: (
        dict[str, str | float | bool | dict[str, Any] | list[Any] | None] | None
    ) = Field(None, description="the customize properties of the model")


class Models2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    name: constr(min_length=1) = Field(..., description="the name of the model")
    ref_sql: constr(min_length=1) | None = Field(
        None, alias="refSql", description="(WIP) the sql reference of the model"
    )
    base_object: constr(min_length=1) | None = Field(
        None, alias="baseObject", description="(WIP) the base object of the model"
    )
    table_reference: TableReference = Field(
        ..., alias="tableReference", description="the table reference of the model"
    )
    columns: list[Column] | None = Field(None, description="the list of columns")
    primary_key: str | None = Field(
        None,
        alias="primaryKey",
        description="the primary key of the model. It's required if the model is the one side of any OEN_TO_MANY or MANY_TO_ONE relationship",
    )
    cached: bool | None = Field(
        None, description="(WIP) whether the model is cached or not"
    )
    refresh_time: constr(pattern=r"^\s*(\d+(?:\.\d+)?)\s*([a-zA-Z]+)\s*$") | None = (
        Field(
            None,
            alias="refreshTime",
            description="(WIP) the cache refresh time of the model",
        )
    )
    row_level_access_controls: list[RowLevelAccessControl] | None = Field(
        None, alias="rowLevelAccessControls"
    )
    properties: (
        dict[str, str | float | bool | dict[str, Any] | list[Any] | None] | None
    ) = Field(None, description="the customize properties of the model")


class Metric(BaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    name: constr(min_length=1) = Field(..., description="the name of the metric")
    base_object: constr(min_length=1) = Field(
        ..., alias="baseObject", description="the base object of the metric"
    )
    dimension: list[Column] = Field(..., description="the list of dimensions")
    measure: list[Column] = Field(..., description="the list of measures", min_length=1)
    time_grain: list[TimeGrainItem] | None = Field(
        None, alias="timeGrain", description="the time grain fields of the metric"
    )
    cached: bool | None = None
    refresh_time: constr(pattern=r"^\s*(\d+(?:\.\d+)?)\s*([a-zA-Z]+)\s*$") | None = (
        Field(
            None,
            alias="refreshTime",
            description="the cache refresh time of the metric",
        )
    )
    properties: (
        dict[str, str | float | bool | dict[str, Any] | list[Any] | None] | None
    ) = None


class WrenmdlManifestSchema(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    field_schema: Literal[
        "https://raw.githubusercontent.com/Canner/WrenAI/main/wren-mdl/mdl.schema.json"
    ] = Field(
        "https://raw.githubusercontent.com/Canner/WrenAI/main/wren-mdl/mdl.schema.json",
        alias="$schema",
        description="the schema of WrenMDL",
    )
    catalog: constr(min_length=1) = Field(
        ..., description="the catalog name of WrenMDL"
    )
    schema_: constr(min_length=1) = Field(
        ..., alias="schema", description="the schema name of WrenMDL"
    )
    sample_data_folder: constr(min_length=1) | None = Field(
        None, alias="sampleDataFolder", description="the folder path for sample data"
    )
    data_source: (
        constr(
            pattern=r"^(?:[Bb][Ii][Gg][Qq][Uu][Ee][Rr][Yy]|[Cc][Ll][Ii][Cc][Kk][Hh][Oo][Uu][Ss][Ee]|[Cc][Aa][Nn][Nn][Ee][Rr]|[Tt][Rr][Ii][Nn][Oo]|[Mm][Ss][Ss][Qq][Ll]|[Mm][Yy][Ss][Qq][Ll]|[Pp][Oo][Ss][Tt][Gg][Rr][Ee][Ss]|[Ss][Nn][Oo][Ww][Ff][Ll][Aa][Kk][Ee]|[Dd][Uu][Cc][Kk][Dd][Bb]|[Ll][Oo][Cc][Aa][Ll]_[Ff][Ii][Ll][Ee]|[Ss]3_[Ff][Ii][Ll][Ee]|[Gg][Cc][Ss]_[Ff][Ii][Ll][Ee]|[Mm][Ii][Nn][Ii][Oo]_[Ff][Ii][Ll][Ee]|[Oo][Rr][Aa][Cc][Ll][Ee]|[Aa][Tt][Hh][Ee][Nn][Aa]|[Rr][Ee][Dd][Ss][Hh][Ii][Ff][Tt])$",
            min_length=1,
        )
        | None
    ) = Field(
        None,
        alias="dataSource",
        description="the data source type (case insensitive). Valid values are: BIGQUERY, CLICKHOUSE, CANNER, TRINO, MSSQL, MYSQL, POSTGRES, SNOWFLAKE, DUCKDB, LOCAL_FILE, S3_FILE, GCS_FILE, MINIO_FILE, ORACLE, ATHENA, REDSHIFT",
    )
    models: list[Models | Models1 | Models2] | None = Field(
        None, description="the list of models"
    )
    relationships: list[Relationship] | None = Field(
        None, description="the list of relationships"
    )
    metrics: list[Metric] | None = Field(None, description="(WIP) the list of metrics")
    views: list[View] | None = Field(None, description="the list of views")
    enum_definitions: list[EnumDefinition] | None = Field(
        None, alias="enumDefinitions", description="(WIP) the list of enum definitions"
    )
