# generated by datamodel-codegen:
#   filename:  mdl.schema.json
#   timestamp: 2026-04-15T19:35:07+00:00

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, RootModel, constr
from enum import Enum
from typing import Any, Literal


class TableReference(BaseModel):
    catalog: str | None = None
    schema_: str | None = Field(None, alias="schema")
    table: constr(min_length=1)


class Model(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class JoinType(Enum):
    ONE_TO_ONE = "ONE_TO_ONE"
    ONE_TO_MANY = "ONE_TO_MANY"
    MANY_TO_ONE = "MANY_TO_ONE"
    MANY_TO_MANY = "MANY_TO_MANY"


class Relationship(BaseModel):
    name: constr(min_length=1) = Field(..., description="the name of the relationship")
    models: list[Model] = Field(
        ..., description="the list of models", max_length=2, min_length=2
    )
    joinType: JoinType = Field(..., description="the join type of the relationship")
    condition: constr(min_length=1) = Field(
        ..., description="the condition of the relationship"
    )
    properties: (
        dict[str, str | float | bool | dict[str, Any] | list[Any] | None] | None
    ) = Field(None, description="the customize properties of the relationship")


class DatePart(Enum):
    YEAR = "YEAR"
    QUARTER = "QUARTER"
    MONTH = "MONTH"
    WEEK = "WEEK"
    DAY = "DAY"
    HOUR = "HOUR"
    MINUTE = "MINUTE"
    SECOND = "SECOND"


class TimeGrainItem(BaseModel):
    name: constr(min_length=1) = Field(
        ..., description="the name of the time grain field"
    )
    refColumn: constr(min_length=1) = Field(
        ..., description="the reference column name of the time grain field"
    )
    dateParts: list[DatePart] = Field(
        ..., description="the acceptable time units of the time grain field"
    )


class View(BaseModel):
    name: constr(min_length=1) = Field(..., description="the name of the view")
    statement: constr(min_length=1) = Field(
        ..., description="the sql statement of the view"
    )
    properties: (
        dict[str, str | float | bool | dict[str, Any] | list[Any] | None] | None
    ) = Field(None, description="the customize properties of the view")


class Value(BaseModel):
    name: constr(min_length=1) = Field(..., description="the name of the member")
    value: constr(min_length=1) | None = Field(
        None,
        description="the value of the member. If not provided, the value is the same as the name",
    )
    properties: (
        dict[str, str | float | bool | dict[str, Any] | list[Any] | None] | None
    ) = Field(None, description="the customize properties of the member")


class EnumDefinition(BaseModel):
    name: constr(min_length=1) = Field(..., description="the name of the enum")
    values: list[Value]
    properties: (
        dict[str, str | float | bool | dict[str, Any] | list[Any] | None] | None
    ) = Field(None, description="the customize properties of the enum")


class Operator(Enum):
    EQUALS = "EQUALS"
    NOT_EQUALS = "NOT_EQUALS"
    GREATER_THAN = "GREATER_THAN"
    LESS_THAN = "LESS_THAN"
    GREATER_THAN_OR_EQUALS = "GREATER_THAN_OR_EQUALS"
    LESS_THAN_OR_EQUALS = "LESS_THAN_OR_EQUALS"


class DataType(Enum):
    NUMERIC = "NUMERIC"
    STRING = "STRING"


class Threshold(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: str = Field(..., description="the value of the threshold")
    dataType: DataType = Field(..., description="the data type of the threshold")


class SessionProperty(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(min_length=1) = Field(
        ..., description="the name of the session property"
    )
    required: bool = Field(
        ..., description="whether the session property is required or not"
    )
    defaultExpr: str | None = Field(
        None, description="the default SQL expression of the session property"
    )


class RowLevelAccessControl(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., description="the name of the access-control rule")
    requiredProperties: list[SessionProperty] = Field(
        ..., description="the required properties for the access-control rule"
    )
    condition: str = Field(
        ...,
        description="The condition of the access-control rule. A condition is a SQL expression that evaluates to true or false.",
    )


class ColumnLevelAccessControl(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., description="the name of the access-control rule")
    operator: Operator = Field(
        ..., description="the operator of the access-control rule"
    )
    requiredProperties: list[SessionProperty] = Field(
        ...,
        description="the required properties for the access-control rule",
        max_length=1,
        min_length=1,
    )
    threshold: Threshold | None = Field(
        None, description="the threshold value of the access-control rule"
    )


class Column(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(min_length=1) = Field(..., description="the name of the column")
    type: constr(min_length=1) = Field(..., description="the type of the column")
    relationship: str | None = Field(
        None,
        description="the relationship used by the column. If the type is a relationship, this field is required",
    )
    isCalculated: bool | None = Field(
        None,
        description="whether the column is calculated or not. If the column expression used relationship, this field is required",
    )
    notNull: bool | None = Field(
        None, description="whether the column is not null or not"
    )
    expression: str | None = Field(
        None,
        description="the expression of the column. If the column is calculated, this field is required",
    )
    isHidden: bool | None = Field(
        None, description="whether the column is hidden or not"
    )
    columnLevelAccessControl: ColumnLevelAccessControl | None = Field(
        None, description="the access-control rule for the column"
    )
    properties: dict[str, str] | None = Field(
        None, description="the customize properties of the column"
    )


class Models(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(min_length=1) = Field(..., description="the name of the model")
    refSql: constr(min_length=1) = Field(
        ..., description="(WIP) the sql reference of the model"
    )
    baseObject: constr(min_length=1) | None = Field(
        None, description="(WIP) the base object of the model"
    )
    tableReference: TableReference | None = Field(
        None, description="the table reference of the model"
    )
    columns: list[Column] | None = Field(None, description="the list of columns")
    primaryKey: str | None = Field(
        None,
        description="the primary key of the model. It's required if the model is the one side of any OEN_TO_MANY or MANY_TO_ONE relationship",
    )
    cached: bool | None = Field(
        None, description="(WIP) whether the model is cached or not"
    )
    refreshTime: constr(pattern=r"^\s*(\d+(?:\.\d+)?)\s*([a-zA-Z]+)\s*$") | None = (
        Field(None, description="(WIP) the cache refresh time of the model")
    )
    rowLevelAccessControls: list[RowLevelAccessControl] | None = None
    properties: (
        dict[str, str | float | bool | dict[str, Any] | list[Any] | None] | None
    ) = Field(None, description="the customize properties of the model")


class Models1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(min_length=1) = Field(..., description="the name of the model")
    refSql: constr(min_length=1) | None = Field(
        None, description="(WIP) the sql reference of the model"
    )
    baseObject: constr(min_length=1) = Field(
        ..., description="(WIP) the base object of the model"
    )
    tableReference: TableReference | None = Field(
        None, description="the table reference of the model"
    )
    columns: list[Column] | None = Field(None, description="the list of columns")
    primaryKey: str | None = Field(
        None,
        description="the primary key of the model. It's required if the model is the one side of any OEN_TO_MANY or MANY_TO_ONE relationship",
    )
    cached: bool | None = Field(
        None, description="(WIP) whether the model is cached or not"
    )
    refreshTime: constr(pattern=r"^\s*(\d+(?:\.\d+)?)\s*([a-zA-Z]+)\s*$") | None = (
        Field(None, description="(WIP) the cache refresh time of the model")
    )
    rowLevelAccessControls: list[RowLevelAccessControl] | None = None
    properties: (
        dict[str, str | float | bool | dict[str, Any] | list[Any] | None] | None
    ) = Field(None, description="the customize properties of the model")


class Models2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(min_length=1) = Field(..., description="the name of the model")
    refSql: constr(min_length=1) | None = Field(
        None, description="(WIP) the sql reference of the model"
    )
    baseObject: constr(min_length=1) | None = Field(
        None, description="(WIP) the base object of the model"
    )
    tableReference: TableReference = Field(
        ..., description="the table reference of the model"
    )
    columns: list[Column] | None = Field(None, description="the list of columns")
    primaryKey: str | None = Field(
        None,
        description="the primary key of the model. It's required if the model is the one side of any OEN_TO_MANY or MANY_TO_ONE relationship",
    )
    cached: bool | None = Field(
        None, description="(WIP) whether the model is cached or not"
    )
    refreshTime: constr(pattern=r"^\s*(\d+(?:\.\d+)?)\s*([a-zA-Z]+)\s*$") | None = (
        Field(None, description="(WIP) the cache refresh time of the model")
    )
    rowLevelAccessControls: list[RowLevelAccessControl] | None = None
    properties: (
        dict[str, str | float | bool | dict[str, Any] | list[Any] | None] | None
    ) = Field(None, description="the customize properties of the model")


class Metric(BaseModel):
    name: constr(min_length=1) = Field(..., description="the name of the metric")
    baseObject: constr(min_length=1) = Field(
        ..., description="the base object of the metric"
    )
    dimension: list[Column] = Field(..., description="the list of dimensions")
    measure: list[Column] = Field(..., description="the list of measures", min_length=1)
    timeGrain: list[TimeGrainItem] | None = Field(
        None, description="the time grain fields of the metric"
    )
    cached: bool | None = None
    refreshTime: constr(pattern=r"^\s*(\d+(?:\.\d+)?)\s*([a-zA-Z]+)\s*$") | None = (
        Field(None, description="the cache refresh time of the metric")
    )
    properties: (
        dict[str, str | float | bool | dict[str, Any] | list[Any] | None] | None
    ) = None


class WrenmdlManifestSchema(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Literal[
        "https://raw.githubusercontent.com/Canner/WrenAI/main/wren-mdl/mdl.schema.json"
    ] = Field(
        "https://raw.githubusercontent.com/Canner/WrenAI/main/wren-mdl/mdl.schema.json",
        alias="$schema",
        description="the schema of WrenMDL",
    )
    catalog: constr(min_length=1) = Field(
        ..., description="the catalog name of WrenMDL"
    )
    schema_: constr(min_length=1) = Field(
        ..., alias="schema", description="the schema name of WrenMDL"
    )
    sampleDataFolder: constr(min_length=1) | None = Field(
        None, description="the folder path for sample data"
    )
    dataSource: (
        constr(
            pattern=r"^(?:[Bb][Ii][Gg][Qq][Uu][Ee][Rr][Yy]|[Cc][Ll][Ii][Cc][Kk][Hh][Oo][Uu][Ss][Ee]|[Cc][Aa][Nn][Nn][Ee][Rr]|[Tt][Rr][Ii][Nn][Oo]|[Mm][Ss][Ss][Qq][Ll]|[Mm][Yy][Ss][Qq][Ll]|[Pp][Oo][Ss][Tt][Gg][Rr][Ee][Ss]|[Ss][Nn][Oo][Ww][Ff][Ll][Aa][Kk][Ee]|[Dd][Uu][Cc][Kk][Dd][Bb]|[Ll][Oo][Cc][Aa][Ll]_[Ff][Ii][Ll][Ee]|[Ss]3_[Ff][Ii][Ll][Ee]|[Gg][Cc][Ss]_[Ff][Ii][Ll][Ee]|[Mm][Ii][Nn][Ii][Oo]_[Ff][Ii][Ll][Ee]|[Oo][Rr][Aa][Cc][Ll][Ee]|[Aa][Tt][Hh][Ee][Nn][Aa]|[Rr][Ee][Dd][Ss][Hh][Ii][Ff][Tt])$",
            min_length=1,
        )
        | None
    ) = Field(
        None,
        description="the data source type (case insensitive). Valid values are: BIGQUERY, CLICKHOUSE, CANNER, TRINO, MSSQL, MYSQL, POSTGRES, SNOWFLAKE, DUCKDB, LOCAL_FILE, S3_FILE, GCS_FILE, MINIO_FILE, ORACLE, ATHENA, REDSHIFT",
    )
    models: list[Models | Models1 | Models2] | None = Field(
        None, description="the list of models"
    )
    relationships: list[Relationship] | None = Field(
        None, description="the list of relationships"
    )
    metrics: list[Metric] | None = Field(None, description="(WIP) the list of metrics")
    views: list[View] | None = Field(None, description="the list of views")
    enumDefinitions: list[EnumDefinition] | None = Field(
        None, description="(WIP) the list of enum definitions"
    )
